version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    volumes:
      - mlflow_db:/mlflow
    command: >
      mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --serve-artifacts --artifacts-destination s3://${S3_BUCKET_NAME}/mlflow-artifacts --host 0.0.0.0
    ports:
      - "5000:5000"

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.serve
    depends_on:
      - redis
      - mlflow
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_REGISTRY_URI: http://mlflow:5000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
    ports:
      - "8000:8000"

  producer:
    build:
      context: .
      dockerfile: docker/Dockerfile.producer
    depends_on:
      - redis

  consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile.consumer
    container_name: consumer
    depends_on:
      - redis
      - mlflow
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_REGISTRY_URI: http://mlflow:5000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    ports:
      - "8001:8001"


  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - consumer

  grafana:
    image: grafana/grafana:10.4.1
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.

volumes:
  mlflow_db: {}
  grafana_data: {}
